### ISSUE TITLE
New release for recent bug fixes

### ISSUE THREAD

**Issue by wexo-team** [DIBS-Payment-Services/magento2-flexwin#45]
Hello @maxwhite 

You recently merged following merge request: 

https://github.com/DIBS-Payment-Services/magento2-flexwin/pull/44

However there is no new release with the changed file. 

Will you create a new release for this?

**Comment by Pr00xxy** [comment]
@wexo-team a new release was created yesterday. Should fix your problem?

**Comment by maxwhite** [comment]
HI @Pr00xxy 
there is new changes in the latest release:
https://github.com/DIBS-Payment-Services/magento2-flexwin/blob/master/view/frontend/layout/dibsflexwin_index_request.xml
or what do you mean ?

**Comment by Pr00xxy** [comment]
@maxwhite I was simply responding to the initial question that @wexo-team made.
