### ISSUE TITLE
Undefined index params when FPC is enabled

### ISSUE THREAD

**Issue by trenox2121** [DIBS-Payment-Services/magento2-flexwin#47]
Magento 2.3.5
Full page cache is enabled.
On url /dibsflexwin/index/request?paytype=VISA getting ```1 exception(s):
Exception #0 (Exception): Notice: Undefined index: params in /vendor/dibs/module-payment-flexwin/view/frontend/templates/form.phtml on line 4```

```\Dibs\Flexwin\Model\Method::collectRequestParams``` set's this error when order is not loaded from checkout session.

**Comment by denis-zyk** [comment]
The issue appears to be fixed in the latest version of the module (2.5.3).

**Comment by trenox2121** [comment]
Fixed with version upgrade to 2.5.3
