### ISSUE TITLE
\Dibs\Flexwin\Controller\Index does not implement CsrfAwareActionInterface

### ISSUE THREAD

**Issue by Lukas-G21** [DIBS-Payment-Services/magento2-flexwin#49]
- Magento 2.3.5
- Dibs_Flexwin 2.5.3

**\Dibs\Flexwin\Controller\Index** does not implement **Magento\Framework\App\CsrfAwareActionInterface** and it's methods thus causing order failure on accept from Nets returning invalid form key error on Magento side.

**Comment by maxwhite** [comment]
Hi @Lukas-G21 , 
can you look at this workaround:
https://github.com/DIBS-Payment-Services/magento2-flexwin/blob/master/Plugin/CsrfValidatorSkip.php
or it doesn't work for you ?

**Comment by Lukas-G21** [comment]
Hi @maxwhite ,
Small correction to issue. Debugged your given plugin. When request action name is **accept** it returns invalid form key error on Magento. When I apply a patch to dibs it works fine. Here's the patch: 

```
diff --git a/Controller/Index.php b/Controller/Index.php
index 8e298db9..b530caf5 100644
@@ -3,8 +3,11 @@
 namespace Dibs\Flexwin\Controller;
 
 use \Dibs\Flexwin\Model\Method as Method;
+use Magento\Framework\App\CsrfAwareActionInterface;
+use Magento\Framework\App\RequestInterface;
+use Magento\Framework\App\Request\InvalidRequestException;
 
-abstract class Index extends \Magento\Framework\App\Action\Action
+abstract class Index extends \Magento\Framework\App\Action\Action implements CsrfAwareActionInterface
 {
     /**
      *
@@ -60,4 +63,21 @@
               && $this->method->checkProtectCode($this->getRequest()->getParam(Method::KEY_ORDERID_NAME),
                  $this->getRequest()->getParam(Method::KEY_ORDER_PROTECT_CODE));
     }
+
+    /**
+     * @inheritDoc
+     */
+    public function createCsrfValidationException(
+        RequestInterface $request
+    ): ?InvalidRequestException {
+        return null;
+    }
+
+    /**
+     * @inheritDoc
+     */
+    public function validateForCsrf(RequestInterface $request): ?bool
+    {
+        return true;
+    }
 }
```

**Comment by maxwhite** [comment]
Hi @Lukas-G21 , 
have you tried to add 'accept' to the array ?
        if ('dibsflexwin' == $request->getModuleName() && in_array($request->getActionName(), ['callback', 'cancel'])) {
in the plugin
https://github.com/DIBS-Payment-Services/magento2-flexwin/blob/24a1f32a90a8b4746c5e944e18295213620b8aae/Plugin/CsrfValidatorSkip.php#L17

The reason why we use plugin instead of implementing CSRF intreface is to make the module compatible with all 2.x versions

**Comment by Lukas-G21** [comment]
@maxwhite ,
Adding 'accept' to array makes it work, will use it in patch instead of implementing CSRF interface in patch.
